site_name: Die Lernende Organisation im 21. Jahrhundert
site_url: https://simondueckert.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Willkommen: index.md
    - Grundlagen:
      - Überblick: 1-1-Grundidee.md
      - Lebenszyklus: 1-2-Lebenszyklus.md
      - Inhaltsverzeichnis: 1-3-Inhaltsverzeichnis.md
      - Inhalt und Schreibstil: 1-4-Inhalt-Schreibstil.md
      - Markdown Syntax: 1-5-Markdown-Syntax.md
      - Produktionskette: 1-6-Produktionskette.md
      - GitHub: 1-7-Github.md
    - Lernpfad: 2-0-Lernpfad.md
    - Anhang: 3-0-Anhang.md
    - Download:
      - PDF-Version: https://github.com/simondueckert/lernorg21/blob/master/de/build/lernorg21.pdf
      - Word-Version: https://github.com/simondueckert/lernorg21/blob/master/de/build/lernorg21.docx
      - HTML-Version: https://github.com/simondueckert/lernorg21/blob/master/de/build/lernorg21.html
      - E-Book (epub): https://github.com/simondueckert/lernorg21/blob/master/de/build/lernorg21.epub
    - Links:
      - cogneon.de: https://cogneon.de
      - CONNECT Community: https://community.cogneon.de

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
      primary: yellow
    scheme: default
    language: de
    icon:
      logo: material/star
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

repo_name: 'simondueckert/lernorg21'
repo_url: 'https://github.com/simondueckert/lernorg21'

extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@simondueckert'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/in/simondueckert/'
        - icon: fontawesome/brands/github
          link: 'https://github.com/simondueckert'
    disqus: lernos
    analytics:
       provider: custom

plugins:
  - search
